### ISSUE TITLE
Can't seem to get it running, using example config.json and docker-compose

### ISSUE THREAD

**Issue by blasphemite** [akshat1/video-hoarder-example#1]
Not really sure what I'm doing wrong. Just getting a blank white page. Using the default config, just changing the paths of data and download directories. Not sure how to interpret the logs, but hostip:7200/video-hoarder is a blank white page.

I had it pop up with a login page once, but I restarted the container and never saw it again.

**Comment by akshat1** [comment]
Hi @blasphemite. I have seen some issues on the front-end (service worker and caching). Would you mind checking if there's anything in your browser console (view -> developer -> javascript console)?

**Comment by blasphemite** [comment]
`Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1930`

`Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. main.js:67`

`[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 284"  data: no] FaviconLoader.jsm:284:24`

`Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. 2 main.js:67`

**Comment by blasphemite** [comment]
`[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 284"  data: no]`

**Comment by blasphemite** [comment]
`The script from “https://my.domain.com/video-hoarder/static/app.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.`

`Uncaught SyntaxError: expected expression, got '<'`

**Comment by akshat1** [comment]
Thanks for the detailed error message @blasphemite. What's happening is that video-hoarder is serving the index page at the URL which is supposed to provide the JavaScript; the server code clearly has some issues to be ironed out. I'm afraid I haven't been able to work on this for the last few days, but I'm hoping to be able to take a look this coming weekend.

In the meantime, if you want to fiddle with it, here's the configuration which I use on my server

### nginx
```
location /video-hoarder/ {
      proxy_pass http://myserver:7200/;
      proxy_redirect http:// https://;
      proxy_set_header Host $host:$server_port;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
```

### video-hoarder; config.json
```json
{
  "serverPath": "/video-hoarder",
  "serverPort": 7200
}
```

### docker-compose

```yaml
version: '3'

services:
  vhoarder-a:
    image: simiacode/video-hoarder:release-0.1.0-rc1
    container_name: video-hoarder
    restart: unless-stopped
    tty: false
    network_mode: bridge
    volumes:
      - /dockerstuff/video-hoarder:/app/db-data
      - /downloads/videos/:/app/download
      - ./config.json:/app/config.json
    ports:
      - 7200:7200
```

In my case, I access it at `https://myserver/video-hoarder`.
